import CentralisedData from './contex'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <CentralisedData>
        {children}
        </CentralisedData>
      </body>
    </html>
  )
}
